name: Markdown Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e
      with:
        config: '.markdownlint.json'
        globs: |
          README.md
          docs/**/*.md
          !docs/changelog.md
          .github/*.md
