name: Python Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@39eb6c9dde236bbc368681611e63120a6eb4afac
        with:
          version: "0.7.13"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Lint imports
        run: |
          ruff check . --select I

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Type check with mypy
        run: |
          uv run mypy .
